name: 💡 GIT Publish

on:
    workflow_dispatch:

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@master
            - name: Publish to GitHub Package Registry
              uses: actions/setup-node@master
              with:
                node-version: 16
                registry-url: https://npm.pkg.github.com
                scope: '@ManojTGN'
            - run: npm ci
            - run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
