name: 💡 Manual workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select a registry'
        required: true
        type: choice
        options:
          - 'both'
          - 'npm'
          - 'github'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Package Registry
        if: ${{ github.event.inputs.choice == 'both' || github.event.inputs.choice == 'github' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm Registry
        if: ${{ github.event.inputs.choice == 'both' || github.event.inputs.choice == 'npm' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm publish --access public --registry=https:registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}
