name: 💡 NPM Publish

on:
    workflow_dispatch:

jobs:
    push:
        name: 💡 NPM Publish
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v3.5.2
              - uses: actions/setup-node@2.5.2
                with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
              - run: npm publish --access public
                env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
